---
#*** Traffic Classification Config for nmeta
#*** Written in YAML
#
#*** max bytes of new flow packets to send to controller:
miss_send_len: 1500
#
#*** Tell switch how to handle fragments (see OpenFlow spec)
ofpc_frag: 0
#
#========== SYSLOG ==================================
#*** Set to 1 if want to log to syslog:
syslog_enabled: 0
#
#*** Where to send syslog (use localhost to keep on-box):
loghost: localhost
#
#*** Port number to send on:
logport: 514
#
#*** Facility to use:
logfacility: 19
#
#*** Syslog Log Format:
syslog_format: "sev=%(levelname)s module=%(module)s func=%(funcName)s %(message)s"
#
#*** Syslog Logging Levels Per Module
#*** Values can be one of CRITICAL|ERROR|WARNING|INFO|DEBUG:
nmeta_logging_level_s: INFO
config_logging_level_s: INFO
policy_logging_level_s: INFO
tc_static_logging_level_s: INFO
tc_identity_logging_level_s: INFO
tc_custom_logging_level_s: INFO
switches_logging_level_s: INFO
forwarding_logging_level_s: INFO
api_logging_level_s: INFO
flows_logging_level_s: INFO
identities_logging_level_s: INFO
api_external_logging_level_s: INFO
#
#========== CONSOLE LOGGING =========================
#*** Set to 1 if want to log to console:
console_log_enabled: 1
#
#*** Set to 1 if you want colorised logs in terminal:
coloredlogs_enabled: 1
#
#*** Console Log Format:
console_format: "%(asctime)s %(module)s[%(process)d] %(funcName)s %(levelname)s %(message)s"
#
#*** Console Logging Levels Per Module
#*** Values can be one of CRITICAL|ERROR|WARNING|INFO|DEBUG:
nmeta_logging_level_c: INFO
config_logging_level_c: INFO
policy_logging_level_c: INFO
tc_static_logging_level_c: INFO
tc_identity_logging_level_c: INFO
tc_custom_logging_level_c: INFO
switches_logging_level_c: INFO
forwarding_logging_level_c: INFO
api_logging_level_c: INFO
flows_logging_level_c: INFO
identities_logging_level_c: INFO
api_external_logging_level_c: INFO
#
#========== Flow Tables ==========================
#*** Maximum idle time for suppression flow entries in seconds.
suppress_idle_timeout: 30
suppress_hard_timeout: 0
#*** Priority for suppression flow entries:
suppress_priority: 1
#
#*** Maximum idle time for drop flow entries in seconds.
drop_idle_timeout: 3600
drop_hard_timeout: 0
#*** Priority for drop flow entries:
drop_priority: 2
#
#========== Mongodb Database ==========================
mongo_addr: localhost
mongo_port: 27017
mongo_dbname: nmeta_database
#
#*** flows packet_ins capped collection
packet_ins_max_bytes: 2000000
flow_time_limit: 30
#
#*** pi_time (packet-in processing time) capped collection
pi_time_max_bytes: 200000
#
#*** flow_rems capped collection
flow_rems_max_bytes: 500000
#
#*** flow_mods capped collection
flow_mods_max_bytes: 500000
#
#*** identities capped collection
identities_max_bytes: 2000000
identity_time_limit: 86400
#
#*** classifications capped collection
classifications_max_bytes: 2000000
classification_time_limit: 86400
#
#*** dhcp_messages capped collection
dhcp_messages_max_bytes: 2000000
dhcp_messages_time_limit: 4492800
#
#========== External API =============================
#*** External API version used in base of URL:
external_api_version: v1
#*** Decision Host IP Address. Use 0.0.0.0 for all NICs:
external_api_host: 0.0.0.0
#*** Decision API TCP port:
external_api_port: 8081
#*** Disable HATEOAS:
external_api_hateoas: False
#*** Extra Eve Debug (use values True or False).
#***  Be aware that this causes whole program to restart:
external_api_debug: False
