---
#*** Main Policy for nmeta - Static Regression Test
#*** Written in YAML
#
tc_rules:
    # Traffic Classification Rulesets and Rules
    tc_ruleset_1:
        - comment: Control Static Rule that doesn't do anything
          match_type: any
          conditions_list:
              - match_type: any
                tcp_src: 123
          actions:
              set_desc: "Foo"
#
qos_treatment:
  # Control Quality of Service (QoS) treatment mapping of
  #  names to output queue numbers:
  default_priority: 0
  constrained_bw: 1
  high_priority: 2
  low_priority: 3
#
port_sets:
    # Port Sets control what data plane ports policies and
    #  features are applied on:
    port_set_location_internal:
        - VirtualSwitch1:
            DPID: 8796748549206
            ports: 1-3,5,66
        - 'VirtualSwitch2':
            DPID: 255
            ports: 3,5
    port_set_location_external:
        - VirtualSwitch1:
            DPID: 8796748549206
            ports: 6
        - 'VirtualSwitch2':
            DPID: 255
            ports: 1-2,4
#
locations:
    # Locations are logical groupings of ports. Takes first match.
    locations_list:
        - internal:
            - port_set_location_internal
        - external:
            - port_set_location_external
    default_match: external


